-- Create DB, schema, and raw table
CREATE DATABASE IF NOT EXISTS CONSUMER_COMPLAINTS_DB;
CREATE SCHEMA IF NOT EXISTS CONSUMER_COMPLAINTS_DB.RAW;
CREATE TABLE IF NOT EXISTS CONSUMER_COMPLAINTS_DB.RAW.RAW__CONSUMER_COMPLAINTS;

-- Use security role
USE ROLE SECURITYADMIN;

-- Create role
CREATE ROLE IF NOT EXISTS MARTS_ROLE;

-- Grant DB usage
GRANT USAGE ON DATABASE SKYTRAX_REVIEWS_DB TO ROLE MARTS_ROLE;
GRANT USAGE ON DATABASE CONSUMER_COMPLAINTS_DB TO ROLE MARTS_ROLE;

-- Grant schema usage
GRANT USAGE ON SCHEMA SKYTRAX_REVIEWS_DB.MARTS TO ROLE MARTS_ROLE;
GRANT USAGE ON SCHEMA CONSUMER_COMPLAINTS_DB.MARTS TO ROLE MARTS_ROLE;

-- Grant select on current tables
GRANT SELECT ON ALL TABLES IN SCHEMA SKYTRAX_REVIEWS_DB.MARTS TO ROLE MARTS_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA CONSUMER_COMPLAINTS_DB.MARTS TO ROLE MARTS_ROLE;

-- Grant select on future tables
GRANT SELECT ON FUTURE TABLES IN SCHEMA SKYTRAX_REVIEWS_DB.MARTS TO ROLE MARTS_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CONSUMER_COMPLAINTS_DB.MARTS TO ROLE MARTS_ROLE;

-- Create user
SET my_user = 'TRANG_DAM';
CREATE USER IF NOT EXISTS IDENTIFIER($my_user)
  PASSWORD = ''
  DEFAULT_ROLE = MARTS_ROLE
  DEFAULT_WAREHOUSE = COMPUTE_WH
  MUST_CHANGE_PASSWORD = FALSE;

-- Grant role to user
GRANT ROLE MARTS_ROLE TO USER IDENTIFIER($my_user);

-- Show users
SHOW USERS;
